name: Kevin Min
markdown: kramdown
url: "https://kevinmin95.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/blog/:year/:month/:day/:title
collections:
  authors:
    output : true
