name: Kevin Min
markdown: kramdown
url: "https://kevinmin95.github.io"
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"



collections:
  authors:
    output : true
